<?php

namespace Jlonom\AllegroSDK\Model;

class ChangePriceWithoutOutput extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];
    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The unique command id generated by you. This should be the same UUID as used in the path.
     *
     * @var string
     */
    protected $id;
    /**
     * The input of the command, i.e. the new Buy Now price for the offer.
     *
     * @var ChangePriceInput
     */
    protected $input;
    /**
     * The unique command id generated by you. This should be the same UUID as used in the path.
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }
    /**
     * The unique command id generated by you. This should be the same UUID as used in the path.
     *
     * @param string $id
     *
     * @return self
     */
    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;
        return $this;
    }
    /**
     * The input of the command, i.e. the new Buy Now price for the offer.
     *
     * @return ChangePriceInput
     */
    public function getInput(): ChangePriceInput
    {
        return $this->input;
    }
    /**
     * The input of the command, i.e. the new Buy Now price for the offer.
     *
     * @param ChangePriceInput $input
     *
     * @return self
     */
    public function setInput(ChangePriceInput $input): self
    {
        $this->initialized['input'] = true;
        $this->input = $input;
        return $this;
    }
}