<?php

namespace Jlonom\AllegroSDK\Model;

class CustomerReturnReturnParcel extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];
    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * 
     *
     * @var \DateTime
     */
    protected $createdAt;
    /**
     * 
     *
     * @var string
     */
    protected $waybill;
    /**
     * Waybill id as generated by carriers physically transporting the parcel. Will be null if there's only one carrier involved in a parcel shipment.
     *
     * @var string|null
     */
    protected $transportingWaybill;
    /**
     * 
     *
     * @var string
     */
    protected $carrierId;
    /**
     * Carrier id of a carrier physically transporting the parcel. Will be null if there's only one carrier involved in a parcel shipment.
     *
     * @var string|null
     */
    protected $transportingCarrierId;
    /**
     * 
     *
     * @var CustomerReturnParcelSender
     */
    protected $sender;
    /**
     * 
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }
    /**
     * 
     *
     * @param \DateTime $createdAt
     *
     * @return self
     */
    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->initialized['createdAt'] = true;
        $this->createdAt = $createdAt;
        return $this;
    }
    /**
     * 
     *
     * @return string
     */
    public function getWaybill(): string
    {
        return $this->waybill;
    }
    /**
     * 
     *
     * @param string $waybill
     *
     * @return self
     */
    public function setWaybill(string $waybill): self
    {
        $this->initialized['waybill'] = true;
        $this->waybill = $waybill;
        return $this;
    }
    /**
     * Waybill id as generated by carriers physically transporting the parcel. Will be null if there's only one carrier involved in a parcel shipment.
     *
     * @return string|null
     */
    public function getTransportingWaybill(): ?string
    {
        return $this->transportingWaybill;
    }
    /**
     * Waybill id as generated by carriers physically transporting the parcel. Will be null if there's only one carrier involved in a parcel shipment.
     *
     * @param string|null $transportingWaybill
     *
     * @return self
     */
    public function setTransportingWaybill(?string $transportingWaybill): self
    {
        $this->initialized['transportingWaybill'] = true;
        $this->transportingWaybill = $transportingWaybill;
        return $this;
    }
    /**
     * 
     *
     * @return string
     */
    public function getCarrierId(): string
    {
        return $this->carrierId;
    }
    /**
     * 
     *
     * @param string $carrierId
     *
     * @return self
     */
    public function setCarrierId(string $carrierId): self
    {
        $this->initialized['carrierId'] = true;
        $this->carrierId = $carrierId;
        return $this;
    }
    /**
     * Carrier id of a carrier physically transporting the parcel. Will be null if there's only one carrier involved in a parcel shipment.
     *
     * @return string|null
     */
    public function getTransportingCarrierId(): ?string
    {
        return $this->transportingCarrierId;
    }
    /**
     * Carrier id of a carrier physically transporting the parcel. Will be null if there's only one carrier involved in a parcel shipment.
     *
     * @param string|null $transportingCarrierId
     *
     * @return self
     */
    public function setTransportingCarrierId(?string $transportingCarrierId): self
    {
        $this->initialized['transportingCarrierId'] = true;
        $this->transportingCarrierId = $transportingCarrierId;
        return $this;
    }
    /**
     * 
     *
     * @return CustomerReturnParcelSender
     */
    public function getSender(): CustomerReturnParcelSender
    {
        return $this->sender;
    }
    /**
     * 
     *
     * @param CustomerReturnParcelSender $sender
     *
     * @return self
     */
    public function setSender(CustomerReturnParcelSender $sender): self
    {
        $this->initialized['sender'] = true;
        $this->sender = $sender;
        return $this;
    }
}